/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsetCreateRouteImport } from './routes/cardset/create'
import { Route as CardsetSetIdRouteImport } from './routes/cardset/$setId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsetCreateRoute = CardsetCreateRouteImport.update({
  id: '/cardset/create',
  path: '/cardset/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsetSetIdRoute = CardsetSetIdRouteImport.update({
  id: '/cardset/$setId',
  path: '/cardset/$setId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cardset/$setId': typeof CardsetSetIdRoute
  '/cardset/create': typeof CardsetCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cardset/$setId': typeof CardsetSetIdRoute
  '/cardset/create': typeof CardsetCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cardset/$setId': typeof CardsetSetIdRoute
  '/cardset/create': typeof CardsetCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/cardset/$setId' | '/cardset/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/cardset/$setId' | '/cardset/create'
  id: '__root__' | '/' | '/about' | '/cardset/$setId' | '/cardset/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardsetSetIdRoute: typeof CardsetSetIdRoute
  CardsetCreateRoute: typeof CardsetCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardset/create': {
      id: '/cardset/create'
      path: '/cardset/create'
      fullPath: '/cardset/create'
      preLoaderRoute: typeof CardsetCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardset/$setId': {
      id: '/cardset/$setId'
      path: '/cardset/$setId'
      fullPath: '/cardset/$setId'
      preLoaderRoute: typeof CardsetSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardsetSetIdRoute: CardsetSetIdRoute,
  CardsetCreateRoute: CardsetCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
